### ISSUE TITLE
Copy Writing Proposal

### ISSUE THREAD

**Issue by Gallantmayor** [Rhotimee/weconnect#57]
Hello, i just checked your lovely project and i discovered you have some sections missing out like FAQ, about us, contact us and privacy policy. If you dont mind i will like to write that for you.
My email: gallantmayor22@gmail.com

**Comment by Rhotimee** [comment]
Thank You for the interest @Gallantmayor but I'm expected to work on the project myself.
You can fork it and add some other stuff though.
